type Profile = { chainId?: string; tokenAddress?: string };
type Pair = { dexId?:string; pairAddress?:string; pairCreatedAt?:number; baseToken?:{address?:string;name?:string;symbol?:string}; priceUsd?:string; marketCap?:number; fdv?:number; liquidity?:{usd?:number}; volume?:{h24?:number;h6?:number;h1?:number;m5?:number}; priceChange?:{h24?:number;h6?:number;h1?:number;m5?:number}; txns?:{h24?:{buys?:number;sells?:number}}; info?:{imageUrl?:string;websites?:Array<{url?:string}>;socials?:Array<{url?:string;type?:string}>} };
const finite=(n:unknown)=>Number.isFinite(Number(n))?Number(n):0;
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
async function json<T>(url:string):Promise<T>{const r=await fetch(url,{headers:{Accept:"application/json","User-Agent":"MemeCoinPredictor/1.1"},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`Market provider returned ${r.status}`);return r.json() as Promise<T>}
export async function GET(){try{
  const [profiles,boosts]=await Promise.all([json<Profile[]>("https://api.dexscreener.com/token-profiles/latest/v1"),json<Profile[]>("https://api.dexscreener.com/token-boosts/top/v1")]);
  const addresses=[...new Set([...profiles,...boosts].filter(p=>p.chainId==="solana"&&p.tokenAddress).map(p=>p.tokenAddress as string))].slice(0,30);
  if(!addresses.length)throw new Error("No Solana tokens returned");
  const pairs=await json<Pair[]>(`https://api.dexscreener.com/tokens/v1/solana/${addresses.join(",")}`),best=new Map<string,Pair>();
  for(const p of pairs){const a=p.baseToken?.address;if(a&&(!best.has(a)||finite(p.liquidity?.usd)>finite(best.get(a)?.liquidity?.usd)))best.set(a,p)}
  const fresh=new Set(profiles.map(p=>p.tokenAddress));
  const tokens=[...best.values()].map(p=>{const marketCap=finite(p.marketCap||p.fdv),liquidity=finite(p.liquidity?.usd),volume=finite(p.volume?.h24),buys=finite(p.txns?.h24?.buys),sells=finite(p.txns?.h24?.sells),buyPct=buys+sells?Math.round(buys/(buys+sells)*100):50,change=finite(p.priceChange?.h24),lr=liquidity/Math.max(marketCap,1);const risk=clamp((lr<.03?42:lr<.08?22:8)+(Math.abs(change)>200?20:0)+(volume>liquidity*20?18:0)+(buys+sells<30?12:0)),score=clamp(35+Math.min(volume/Math.max(marketCap,1)*35,25)+Math.min(lr*100,18)+(buyPct-50)*.55+Math.max(-15,Math.min(change/8,18))-risk*.24);return{id:p.baseToken?.address||p.pairAddress,address:p.baseToken?.address,name:p.baseToken?.name||"Unknown token",symbol:p.baseToken?.symbol||"—",image:p.info?.imageUrl||"",glyph:(p.baseToken?.symbol||"?")[0],accent:score>=75?"#c8ff31":risk>=60?"#ff5571":"#52d9ff",price:finite(p.priceUsd),marketCap,volume,volume1h:finite(p.volume?.h1),volume5m:finite(p.volume?.m5),liquidity,holders:0,holderGrowth:0,change,change1h:finite(p.priceChange?.h1),change5m:finite(p.priceChange?.m5),score,risk,createdAt:p.pairCreatedAt||null,txns:buys+sells,buys:buyPct,tag:fresh.has(p.baseToken?.address)?"NEW PROFILE":"TRENDING",dex:p.dexId||"Solana DEX"}}).filter(t=>t.marketCap>0||t.liquidity>0).sort((a,b)=>b.score-a.score).slice(0,18);
  return Response.json({tokens,source:"DEX Screener",updatedAt:new Date().toISOString(),mode:"live"},{headers:{"Cache-Control":"public, s-maxage=15, stale-while-revalidate=45"}})
}catch(e){return Response.json({tokens:[],mode:"unavailable",error:e instanceof Error?e.message:"Live feed unavailable"},{status:503,headers:{"Cache-Control":"no-store"}})}}
