"use client";

import { useEffect, useMemo, useState } from "react";

type Token={id:string;address?:string;name:string;symbol:string;image?:string;glyph:string;price:number|string;marketCap:number;volume:number;volume1h?:number;volume5m?:number;liquidity:number;change:number;change1h?:number;change5m?:number;score:number;risk:number;createdAt?:number|null;txns:number|string;buys:number;tag:string;age?:string};
type PortfolioHolding={mint:string;balance:number;name:string;symbol:string;image:string;price:number;marketCap:number;change24h:number;value:number;supported:boolean};
type PhantomKey={toString():string};type PhantomProvider={isPhantom?:boolean;publicKey?:PhantomKey|null;connect:(options?:{onlyIfTrusted?:boolean})=>Promise<{publicKey?:PhantomKey}>;disconnect?:()=>Promise<void>;on?:(event:string,handler:(key?:PhantomKey|null)=>void)=>void;off?:(event:string,handler:(key?:PhantomKey|null)=>void)=>void};
const SPL_PROGRAM="TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",SPL_2022="TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",WRAPPED_SOL="So11111111111111111111111111111111111111112";
async function browserWalletBalances(address:string,signal:AbortSignal){const endpoints=["https://api.mainnet-beta.solana.com","https://solana-rpc.publicnode.com","https://solana.drpc.org"],call=async(url:string,method:string,params:unknown[])=>{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:method,method,params}),signal});if(!response.ok)throw new Error(`RPC ${response.status}`);const json=await response.json();if(json.error)throw new Error(json.error.message||"RPC error");return json.result};for(const url of endpoints){try{const config={encoding:"jsonParsed",commitment:"confirmed"},[legacy,modern,sol]=await Promise.all([call(url,"getTokenAccountsByOwner",[address,{programId:SPL_PROGRAM},config]),call(url,"getTokenAccountsByOwner",[address,{programId:SPL_2022},config]),call(url,"getBalance",[address,{commitment:"confirmed"}])]),balances=new Map<string,number>();for(const item of[...(legacy.value||[]),...(modern.value||[])]){const info=item.account?.data?.parsed?.info,mint=info?.mint,amount=Number(info?.tokenAmount?.uiAmount??info?.tokenAmount?.uiAmountString);if(mint&&Number.isFinite(amount)&&amount>0)balances.set(mint,(balances.get(mint)||0)+amount)}const solBalance=Number(sol.value)/1e9;if(solBalance>.000001)balances.set(WRAPPED_SOL,solBalance);return[...balances].map(([mint,balance])=>({mint,balance}))}catch(error){if(signal.aborted)throw error}}throw new Error("Wallet balance providers are unavailable from this browser")}
const fallback:Token[]=[
 {id:"demo1",name:"Pepe Intelligence",symbol:"PEPEAI",glyph:"P",price:.000184,marketCap:748000,volume:312400,liquidity:88600,change:42.8,score:87,risk:32,createdAt:Date.now()-12400000,txns:8492,buys:68,tag:"AI PICK"},
 {id:"demo2",name:"Byte Bandit",symbol:"BYTE",glyph:"B",price:.000091,marketCap:384000,volume:186200,liquidity:61200,change:28.3,score:81,risk:28,createdAt:Date.now()-6800000,txns:5210,buys:64,tag:"TRENDING"},
 {id:"demo3",name:"Neko Protocol",symbol:"NEKO",glyph:"N",price:.000047,marketCap:192000,volume:97800,liquidity:39400,change:67.1,score:76,risk:44,createdAt:Date.now()-2280000,txns:3804,buys:71,tag:"NEW"}
];
const money=(n:number)=>n>=1e6?`$${(n/1e6).toFixed(1).replace(".0","")}M`:n>=1e3?`$${Math.round(n/1e3)}K`:`$${Math.round(n)}`;
const age=(d?:number|null)=>{if(!d)return"Unknown";const m=Math.floor((Date.now()-d)/60000);return m<60?`${m} min`:m<1440?`${Math.floor(m/60)} hr`:`${Math.floor(m/1440)} days`};
const scoreText=(n:number)=>n>=80?"High Potential":n>=60?"Promising":n>=40?"Neutral":n>=20?"Risky":"Very Risky";
const riskText=(n:number)=>n<30?"Low":n<60?"Medium":"High";
const insight=(t:Token)=>t.risk>=65?"Avoid":t.score>=80?"Potential Opportunity":t.score>=60?"Watch":t.change<0?"High Risk":"Watch";
const reason=(t:Token)=>t.risk>=65?"Low liquidity or unusual trading activity increases the chance of sudden losses.":t.buys>=60&&t.change>10?"Buying activity and price momentum are both increasing.":t.volume>t.liquidity*2?"Trading activity is strong compared with available liquidity.":"Market activity is steady, but stronger confirmation is still needed.";
const confidence=(t:Token)=>Math.max(20,Math.min(92,Math.round(28+Math.min(Number(t.txns)/80,25)+Math.min(t.liquidity/Math.max(t.marketCap,1)*100,20)+(t.createdAt&&Date.now()-t.createdAt>3600000?12:3)+(t.volume1h?7:0))));
const momentum=(t:Token)=>{const c=t.change1h??t.change,b=t.buys;return c>30&&b>=65?"Explosive":c>8&&b>=55?"Strong":c>-5&&b>=45?"Stable":c>-20?"Weakening":"Rapidly Falling"};
const health=(t:Token)=>Math.max(5,Math.min(95,Math.round(100-t.risk*.72-Math.max(0,45-t.buys)*.35)));
const healthText=(n:number)=>n>=75?"Healthy":n>=50?"Mixed":n>=30?"Fragile":"High Risk";
const warnings=(t:Token)=>[t.liquidity<t.marketCap*.05?"Liquidity is low compared with market value":null,Number(t.txns)<50?"Limited trading history — signals may change quickly":null,t.volume>t.liquidity*20?"Unusually high volume relative to liquidity":null,(t.change1h??0)<-20?"Momentum is falling rapidly in the last hour":null].filter(Boolean) as string[];
const searchTerm=(value:string)=>{const match=value.match(/[1-9A-HJ-NP-Za-km-z]{32,44}/);return (match?.[0]||value).trim().toLowerCase()};

function Logo({t,large=false}:{t:Token;large?:boolean}){return <span className={`coin ${large?"large":""}`}>{t.image?<img src={t.image} alt=""/>:<b>{t.glyph}</b>}</span>}
function AIScore({value,big=false}:{value:number;big?:boolean}){return <div className={`ai-score ${big?"big":""}`}><strong>{value}</strong><span>/100</span><small>{scoreText(value)}</small></div>}
function RiskBadge({value}:{value:number}){const l=riskText(value);return <span className={`risk ${l.toLowerCase()}`}><i/>{l} risk</span>}
function Signal({t}:{t:Token}){return <div className="signal"><span>✦</span><div><b>{insight(t)}</b><p>{reason(t)}</p></div></div>}
function Skeletons(){return <div className="card-grid">{[1,2,3].map(i=><div className="skeleton" key={i}><i/><b/><span/><span/></div>)}</div>}

function TokenCard({t,watched,onWatch,onOpen,compact=false}:{t:Token;watched:boolean;onWatch:()=>void;onOpen:()=>void;compact?:boolean}){
 return <article className={`token-card ${compact?"compact":""}`}>
  <div className="token-title"><Logo t={t}/><div><h3>{t.name}</h3><p>${t.symbol} · {age(t.createdAt)}</p>{t.address&&<CopyMintButton mint={t.address}/>}</div><RiskBadge value={t.risk}/></div>
  <div className="card-core"><div><small>MARKET CAP</small><strong className="market-cap-value">{money(t.marketCap)}</strong></div><div><small>24H CHANGE</small><strong className={t.change>=0?"positive":"negative"}>{t.change>=0?"+":""}{t.change.toFixed(1)}%</strong></div><AIScore value={t.score}/></div>
  {!compact&&<><Signal t={t}/><div className="trust-row"><span><b>{momentum(t)}</b> momentum</span><span><b>{confidence(t)}%</b> confidence</span></div></>}<div className="actions"><button className="primary" onClick={onOpen}>View analysis</button><button className={watched?"watch saved":"watch"} onClick={onWatch}>{watched?"♥ Saved":"♡ Watch"}</button></div>
 </article>
}

function EmptyState({type,onDiscover,busy=false,error=""}:{type:"watch"|"portfolio";onDiscover:()=>void;busy?:boolean;error?:string}){return <div className="empty"><span>{type==="watch"?"♡":"◫"}</span><h2>{type==="watch"?"Your watchlist is empty":"Connect your Phantom Wallet"}</h2><p>{type==="watch"?"Save tokens you’re interested in and we’ll help you monitor their momentum and risk.":"View your public wallet address and prepare for read-only portfolio analysis. No signing or transaction permission is requested."}</p>{error&&<div className="wallet-error">{error}</div>}<button className="primary" disabled={busy} onClick={onDiscover}>{type==="watch"?"Discover tokens":busy?"Connecting…":"Connect Phantom"}</button>{type==="portfolio"&&<><small>We never ask for your seed phrase, private key, or a transaction signature.</small><div className="phantom-links"><a className="phantom-help" href="https://phantom.app/ul/browse/https%3A%2F%2Fmemecoin-predictor-intel.rabangcarlo.chatgpt.site%2F?ref=https%3A%2F%2Fmemecoin-predictor-intel.rabangcarlo.chatgpt.site" target="_blank" rel="noreferrer">Open inside Phantom mobile ↗</a><a className="phantom-help" href="https://phantom.app/download" target="_blank" rel="noreferrer">Install Phantom ↗</a></div></>}</div>}

function CopyMintButton({mint}:{mint:string}){const[copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard.writeText(mint);setCopied(true);window.setTimeout(()=>setCopied(false),1600)};return <button className={`copy-mint ${copied?"copied":""}`} onClick={copy} title={mint} aria-label={`Copy token address ${mint}`}><span>{copied?"Copied":`${mint.slice(0,4)}...${mint.slice(-4)}`}</span><i className="copy-icon" aria-hidden="true"/></button>}
function ConnectedPortfolio({address,onDisconnect,holdings,loading,error,total,updated}:{address:string;onDisconnect:()=>void;holdings:PortfolioHolding[];loading:boolean;error:string;total:number;updated:string}){const usd=(n:number)=>n.toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:n<1?2:0,maximumFractionDigits:2});return <section className="portfolio-page"><div className="portfolio-head"><div><span className="kicker">READ-ONLY CONNECTION</span><h1>My Portfolio</h1><p>Phantom is connected. Balances and market data refresh automatically.</p></div><button className="watch" onClick={onDisconnect}>Disconnect Wallet</button></div><div className="portfolio-summary"><div><small>PORTFOLIO VALUE</small><strong>{loading&&!holdings.length?"Loading…":usd(total)}</strong></div><div><small>WALLET TOKENS</small><strong>{holdings.length}</strong></div><div><small>LAST UPDATED</small><strong>{updated?new Date(updated).toLocaleTimeString():"—"}</strong></div></div><div className="wallet-card"><span>CONNECTED WALLET</span><strong>{address.slice(0,8)}…{address.slice(-8)}</strong>{loading&&<em>Refreshing…</em>}<button onClick={()=>navigator.clipboard.writeText(address)}>Copy address</button></div>{error&&<div className="portfolio-error">{error}{holdings.length?" Last successful portfolio values remain visible.":""}</div>}{loading&&!holdings.length?<div className="portfolio-loading"><i/><b>Loading wallet tokens…</b><p>Reading public balances and matching live market data.</p></div>:error&&!holdings.length?<div className="portfolio-empty"><b>Wallet tokens could not be loaded</b><p>Your wallet is still connected. The app will retry automatically.</p></div>:!holdings.length?<div className="portfolio-empty"><b>No token balances found</b><p>This wallet does not currently contain SPL tokens or SOL with a visible balance.</p></div>:<div className="holding-list">{holdings.map(h=><article className="holding" key={h.mint}><span className="holding-logo">{h.image?<img src={h.image} alt=""/>:<b>{h.symbol.slice(0,1)}</b>}</span><div className="holding-name"><b>{h.name}</b><small>{h.symbol} · {h.mint.slice(0,5)}…{h.mint.slice(-4)}</small><CopyMintButton mint={h.mint}/></div><div><small>BALANCE</small><b>{h.balance.toLocaleString(undefined,{maximumFractionDigits:6})}</b></div><div><small>PRICE</small><b>{h.supported?usd(h.price):"Unavailable"}</b></div><div><small>MARKET CAP</small><b>{h.marketCap?money(h.marketCap):"Unavailable"}</b></div><div><small>VALUE</small><b>{h.supported?usd(h.value):"Unavailable"}</b></div><div><small>24H</small><b className={h.change24h>=0?"positive":"negative"}>{h.supported?`${h.change24h>=0?"+":""}${h.change24h.toFixed(1)}%`:"—"}</b></div><div><small>PROFIT / LOSS</small><b className="unavailable">Not available</b></div></article>)}</div>}<p className="cost-note">Profit/loss requires verified purchase history or a user-provided cost basis, so it is not estimated from wallet balances.</p></section>}

function Detail({t,onBack,freshness}:{t:Token;onBack:()=>void;freshness:string}){const potential=Math.max(5,Math.min(92,Math.round(t.score*.78-t.risk*.12+12)));const positives=[`${t.buys}% of recorded transactions are buys`,`${money(t.volume)} traded in the last 24 hours`,t.change>=0?`Price is up ${t.change.toFixed(1)}% today`:`Price is down ${Math.abs(t.change).toFixed(1)}% today`];const h=health(t),alerts=warnings(t);return <main className="detail-page">
 <button className="back" onClick={onBack}>← Back</button>
 <section className="detail-intro"><div className="detail-token"><Logo t={t} large/><div><p>LIVE SOLANA MARKET DATA</p><h1>{t.name} <span>${t.symbol}</span></h1><small>{t.address?`${t.address.slice(0,7)}…${t.address.slice(-5)}`:"Example token"} · Updated {freshness}</small></div></div><div className="detail-verdict"><div><small>AI INSIGHT</small><h2>{insight(t)}</h2><p>{reason(t)} Consider this research, not financial advice.</p></div><AIScore value={t.score} big/><RiskBadge value={t.risk}/></div><div className="confidence-grid"><div><small>CONFIDENCE</small><b>{confidence(t)}%</b><p>{confidence(t)<50?"Low confidence — not enough reliable history yet":"How complete and reliable the available data is"}</p></div><div><small>MOMENTUM</small><b>{momentum(t)}</b><p>Based on recent movement and buying pressure</p></div><div><small>TOKEN HEALTH</small><b>{h}/100 · {healthText(h)}</b><p>Liquidity, activity, age, and visible risk</p></div></div></section>
 {alerts.length>0&&<section className="warnings"><span>!</span><div><b>{alerts.length>1?"Important warnings":"Important warning"}</b>{alerts.map(a=><p key={a}>{a}</p>)}</div></section>}
 <div className="simple-columns"><section className="simple-panel"><span className="kicker">WHY IT STANDS OUT</span><h2>Why the model likes it</h2>{positives.map((x,i)=><p className="reason-row good" key={x}><i>↑</i><span>{x}</span></p>)}</section><section className="simple-panel"><span className="kicker">THINGS TO WATCH</span><h2>What could go wrong</h2><p className="reason-row warning"><i>!</i><span>{t.liquidity<t.marketCap*.08?"Liquidity is low compared with its market value":"Liquidity is reasonable, but can change quickly"}</span></p><p className="reason-row warning"><i>!</i><span>{age(t.createdAt)} old — newer tokens are less predictable</span></p><p className="reason-row muted"><i>i</i><span>Whale ownership data is not available from this feed</span></p></section></div>
 <section className="potential"><div><span className="kicker">$1M MARKET CAP POTENTIAL</span><h2>{potential}% <small>{potential>=70?"Promising":potential>=45?"Possible":"Uncertain"}</small></h2><p>A simple estimate based on current momentum, liquidity, activity, and risk.</p></div><div className="potential-bar"><i style={{width:`${potential}%`}}/></div></section>
 <details className="advanced"><summary>Advanced analysis <span>Show market data +</span></summary><div className="metric-grid"><div><small>Market cap</small><b className="market-cap-value">{money(t.marketCap)}</b></div><div><small>24H volume</small><b>{money(t.volume)}</b></div><div><small>Liquidity <em title="Money available for buying and selling this token">ⓘ</em></small><b>{money(t.liquidity)}</b></div><div><small>Buying pressure</small><b>{t.buys}%</b></div><div><small>Transactions</small><b>{Number(t.txns).toLocaleString()}</b></div><div><small>Token age</small><b>{age(t.createdAt)}</b></div></div></details>
 </main>}

export default function Home(){const[page,setPage]=useState("Home"),[tokens,setTokens]=useState<Token[]>([]),[status,setStatus]=useState<"loading"|"live"|"error">("loading"),[refreshing,setRefreshing]=useState(false),[updated,setUpdated]=useState(""),[clock,setClock]=useState(Date.now()),[query,setQuery]=useState(""),[filter,setFilter]=useState("AI Picks"),[advanced,setAdvanced]=useState(false),[watch,setWatch]=useState<string[]>([]),[detail,setDetail]=useState<Token|null>(null),[walletAddress,setWalletAddress]=useState(""),[walletBusy,setWalletBusy]=useState(false),[walletError,setWalletError]=useState(""),[portfolio,setPortfolio]=useState<PortfolioHolding[]>([]),[portfolioLoading,setPortfolioLoading]=useState(false),[portfolioError,setPortfolioError]=useState(""),[portfolioUpdated,setPortfolioUpdated]=useState("");
 useEffect(()=>{setWatch(JSON.parse(localStorage.getItem("mp-watch")||"[]"));let alive=true,loaded=false,controller:AbortController|null=null;const load=async()=>{if(document.hidden)return;controller?.abort();controller=new AbortController();if(loaded)setRefreshing(true);try{const r=await fetch("/api/tokens",{cache:"no-store",signal:controller.signal});if(!r.ok)throw 0;const d=await r.json();if(alive){setTokens(d.tokens);setUpdated(d.updatedAt);setStatus("live");loaded=true}}catch(e){if(alive&&!(e instanceof DOMException&&e.name==="AbortError"))setStatus("error")}finally{if(alive)setRefreshing(false)}};load();const timer=setInterval(load,15000),ticker=setInterval(()=>setClock(Date.now()),1000);const visible=()=>{if(!document.hidden)load()};document.addEventListener("visibilitychange",visible);return()=>{alive=false;controller?.abort();clearInterval(timer);clearInterval(ticker);document.removeEventListener("visibilitychange",visible)}},[]);
 useEffect(()=>{const browserWindow=window as typeof window&{phantom?:{solana?:PhantomProvider};solana?:PhantomProvider};const provider=browserWindow.phantom?.solana||(browserWindow.solana?.isPhantom?browserWindow.solana:undefined);if(!provider)return;let active=true;const changed=(key?:PhantomKey|null)=>{if(!active)return;const next=key?.toString()||"";setWalletAddress(next);setWalletError("");setPortfolio([]);setPortfolioUpdated("");if(next)localStorage.setItem("mp-phantom-connected","1");else localStorage.removeItem("mp-phantom-connected")};const disconnected=()=>changed(null);provider.on?.("accountChanged",changed);provider.on?.("disconnect",disconnected);if(localStorage.getItem("mp-phantom-connected")==="1")provider.connect({onlyIfTrusted:true}).then(r=>{const address=r.publicKey?.toString()||provider.publicKey?.toString()||"";if(address)changed({toString:()=>address})}).catch(()=>localStorage.removeItem("mp-phantom-connected"));return()=>{active=false;provider.off?.("accountChanged",changed);provider.off?.("disconnect",disconnected)}},[]);
 useEffect(()=>{if(!walletAddress){setPortfolio([]);setPortfolioLoading(false);setPortfolioError("");return}let active=true,controller:AbortController|null=null;const request=async(body:unknown,signal:AbortSignal)=>{const response=await fetch("/api/portfolio",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal}),data=await response.json();if(!response.ok)throw new Error(data.error||"Portfolio data is unavailable");return data};const load=async()=>{if(document.hidden)return;controller?.abort();controller=new AbortController();setPortfolioLoading(true);try{let data;try{data=await request({address:walletAddress},controller.signal)}catch{const balances=await browserWalletBalances(walletAddress,controller.signal);data=await request({address:walletAddress,balances},controller.signal)}if(active){setPortfolio(data.holdings);setPortfolioUpdated(data.updatedAt);setPortfolioError("")}}catch(e){if(active&&!(e instanceof DOMException&&e.name==="AbortError"))setPortfolioError(e instanceof Error?e.message:"Portfolio data is unavailable")}finally{if(active)setPortfolioLoading(false)}};load();const timer=setInterval(load,30000);const visible=()=>{if(!document.hidden)load()};document.addEventListener("visibilitychange",visible);return()=>{active=false;controller?.abort();clearInterval(timer);document.removeEventListener("visibilitychange",visible)}},[walletAddress]);
 const all=tokens.length?tokens:fallback;const toggle=(id:string)=>setWatch(w=>{const next=w.includes(id)?w.filter(x=>x!==id):[...w,id];localStorage.setItem("mp-watch",JSON.stringify(next));return next});
 const filtered=useMemo(()=>{const q=searchTerm(query);return all.filter(t=>`${t.name} ${t.symbol} ${t.address||""}`.toLowerCase().includes(q)).filter(t=>filter==="Trending"?t.change>10:filter==="New"?(t.createdAt||0)>Date.now()-86400000:filter==="Low Risk"?t.risk<30:filter==="High Potential"?t.score>=80:true)},[all,query,filter]);
 const freshSeconds=updated?Math.max(0,Math.floor((clock-new Date(updated).getTime())/1000)):0;const stale=status==="error"||freshSeconds>45;const freshness=!updated?"pending":freshSeconds<60?`${freshSeconds}s ago`:`${Math.floor(freshSeconds/60)}m ago`;const runSearch=()=>{if(filtered.length===1)setDetail(filtered[0])};const activeDetail=detail?(tokens.find(t=>t.id===detail.id)||detail):null;
 const connectPhantom=async()=>{if(walletBusy||walletAddress)return;setPage("Portfolio");setWalletBusy(true);setWalletError("");try{const browserWindow=window as typeof window&{phantom?:{solana?:PhantomProvider};solana?:PhantomProvider};const provider=browserWindow.phantom?.solana||(browserWindow.solana?.isPhantom?browserWindow.solana:undefined);let found="";if(provider){const result=await provider.connect();found=result.publicKey?.toString()||""}else{const{BrowserSDK,AddressType}=await import("@phantom/browser-sdk");const sdk=new BrowserSDK({providers:["injected"],addressTypes:[AddressType.solana]});const installed=await sdk.isPhantomInstalled();if(!installed)throw new Error(window.self!==window.top?"This embedded browser cannot access Phantom. Open the app directly in Chrome, Brave, Edge, or inside Phantom mobile.":"Phantom was not detected. Install the extension, refresh this page, or open the app inside Phantom mobile.");const result=await sdk.connect({provider:"injected"});found=result.addresses.find(a=>a.addressType===AddressType.solana)?.address||result.addresses[0]?.address||""}if(!found)throw new Error("Phantom connected, but no Solana address was returned.");localStorage.setItem("mp-phantom-connected","1");setWalletAddress(found)}catch(e){const message=e instanceof Error?e.message:"Wallet connection was cancelled or unavailable.";setWalletError(/reject|cancel/i.test(message)?"Connection was cancelled. Your wallet remains unchanged.":message)}finally{setWalletBusy(false)}};
 const disconnectPhantom=async()=>{const browserWindow=window as typeof window&{phantom?:{solana?:PhantomProvider};solana?:PhantomProvider};const provider=browserWindow.phantom?.solana||(browserWindow.solana?.isPhantom?browserWindow.solana:undefined);try{await provider?.disconnect?.()}catch{}localStorage.removeItem("mp-phantom-connected");setWalletAddress("");setWalletError("");setPortfolio([]);setPortfolioError("");setPortfolioUpdated("")};
 const go=(p:string)=>{setPage(p);setDetail(null)};const nav=["Home","Discover","Watchlist","Portfolio","Alerts"];
 return <div className="app"><header><a className="brand" onClick={()=>go("Home")}><span>MC</span><b>MemeCoin <em>Predictor</em></b></a><nav>{nav.map(n=><button className={page===n?"active":""} onClick={()=>go(n)} key={n}>{n}</button>)}</nav><div className={`live ${status} ${stale?"stale":""} ${refreshing?"refreshing":""}`}><i/>{refreshing?"Updating market caps…":stale?`Data stale · ${freshness}`:`Updated ${freshness}`}</div><button className={`wallet ${walletAddress?"connected":""}`} aria-label={walletAddress?`Phantom Wallet ${walletAddress}`:undefined} onClick={walletAddress?()=>go("Portfolio"):connectPhantom}>{walletAddress?<><span className="phantom-logo" title="Phantom Wallet"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4.2 17.8c.7-1.1 1.2-2.5 1.4-4.1C6.2 8.7 8.8 6 12.5 6c4.3 0 7.1 3.6 7.1 8.6 0 1.8-.5 3.4-1.5 4.5-.4.5-1.2.3-1.4-.3l-.3-1.1-.7 1.2c-.4.6-1.2.5-1.5-.1l-.5-1.1-.8 1.2c-.4.6-1.2.5-1.5-.1l-.6-1.2-.9 1.1c-.5.6-1.4.3-1.5-.4l-.2-1.2c-.8.7-1.7 1.2-2.7 1.5-.8.2-1.6-.2-1.3-.8Z"/><circle cx="10.2" cy="12.5" r="1" className="phantom-eye"/><circle cx="15.1" cy="12.5" r="1" className="phantom-eye"/></svg></span><small>{walletAddress.slice(0,4)}…{walletAddress.slice(-4)}</small></>:walletBusy?"Connecting…":"Connect Phantom"}</button></header>
 {activeDetail?<Detail t={activeDetail} freshness={freshness} onBack={()=>setDetail(null)}/>:<main>{page==="Home"&&<><section className="hero"><div><span className="kicker">YOUR DAILY MEMECOIN BRIEF</span><h1>What looks worth<br/><em>watching today?</em></h1><p>Simple, explainable signals from live Solana market activity. No trading jargon required.</p></div><div className="brief"><span>Market check</span><strong>{all.filter(t=>t.score>=70&&t.risk<60).length} opportunities</strong><p>passed today’s basic momentum and risk checks.</p><small>{stale?`Last successful update ${freshness} · retrying`:`Market caps updated ${freshness}`}</small></div></section><SectionTitle label="TOP RECOMMENDATIONS" title="AI Picks" copy="The strongest opportunities right now, filtered for excessive risk."/>{status==="loading"?<Skeletons/>:<div className="card-grid">{all.filter(t=>t.risk<65).slice(0,3).map(t=><TokenCard key={t.id} t={t} watched={watch.includes(t.id)} onWatch={()=>toggle(t.id)} onOpen={()=>setDetail(t)}/>)}</div>}<div className="two-sections"><section><SectionTitle label="MOVING NOW" title="Trending" copy="Tokens showing clear momentum."/><div className="compact-list">{[...all].sort((a,b)=>b.change-a.change).slice(0,3).map(t=><TokenCard compact key={t.id} t={t} watched={watch.includes(t.id)} onWatch={()=>toggle(t.id)} onOpen={()=>setDetail(t)}/>)}</div></section><section><SectionTitle label="RECENTLY DISCOVERED" title="New opportunities" copy="Newer tokens that passed basic checks."/><div className="compact-list">{all.filter(t=>t.risk<60).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,3).map(t=><TokenCard compact key={t.id} t={t} watched={watch.includes(t.id)} onWatch={()=>toggle(t.id)} onOpen={()=>setDetail(t)}/>)}</div></section></div></>}
 {page==="Discover"&&<><section className="page-head"><span className="kicker">DISCOVER</span><h1>Find your next token to watch</h1><p>Search by name, symbol, contract address, or paste a Pump.fun URL.</p></section><label className="big-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&runSearch()} placeholder="Search token or paste a Pump.fun URL"/><button onClick={runSearch}>Search</button></label><div className="filters">{["AI Picks","Trending","New","Low Risk","High Potential"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}<button className="advanced-btn" onClick={()=>setAdvanced(!advanced)}>Advanced filters {advanced?"−":"+"}</button></div>{advanced&&<div className="advanced-filters"><label>Minimum market cap<input type="number" placeholder="$100,000"/></label><label>Minimum liquidity<input type="number" placeholder="$25,000"/></label><label>Maximum risk<input type="range" min="0" max="100" defaultValue="60"/></label></div>}{filtered.length?<div className="card-grid discover-grid">{filtered.map(t=><TokenCard key={t.id} t={t} watched={watch.includes(t.id)} onWatch={()=>toggle(t.id)} onOpen={()=>setDetail(t)}/>)}</div>:<div className="not-found"><b>Token not found in the current live sample</b><p>Check the contract address or try again after the market feed refreshes.</p></div>}</>}
 {page==="Watchlist"&&(watch.length?<><section className="page-head"><span className="kicker">MY WATCHLIST</span><h1>Tokens you’re monitoring</h1><p>Review how their opportunity and risk signals have changed.</p></section><div className="card-grid">{all.filter(t=>watch.includes(t.id)).map(t=><TokenCard key={t.id} t={t} watched onWatch={()=>toggle(t.id)} onOpen={()=>setDetail(t)}/>)}</div></>:<EmptyState type="watch" onDiscover={()=>go("Discover")}/>)}
 {page==="Portfolio"&&(walletAddress?<ConnectedPortfolio address={walletAddress} onDisconnect={disconnectPhantom} holdings={portfolio} loading={portfolioLoading} error={portfolioError} total={portfolio.reduce((sum,h)=>sum+h.value,0)} updated={portfolioUpdated}/>:<EmptyState type="portfolio" busy={walletBusy} error={walletError} onDiscover={connectPhantom}/>)}{page==="Alerts"&&<div className="empty"><span>♢</span><h2>No alerts yet</h2><p>Alerts for score, price, and risk changes are coming next. Your live dashboard continues to refresh every 20 seconds.</p><button className="primary" onClick={()=>go("Discover")}>Discover tokens</button></div>}</main>}
 <div className="mobile-nav">{nav.slice(0,4).map((n,i)=><button className={page===n?"active":""} onClick={()=>go(n)} key={n}><span>{["⌂","⌕","♡","◫"][i]}</span>{n}</button>)}</div><footer><b>Research, not financial advice.</b><span>Scores use live third-party data that may be delayed or incomplete. Meme coins are highly risky.</span></footer></div>}

function SectionTitle({label,title,copy}:{label:string;title:string;copy:string}){return <div className="section-title"><span className="kicker">{label}</span><h2>{title}</h2><p>{copy}</p></div>}
