type TokenAccount={account?:{data?:{parsed?:{info?:{mint?:string;tokenAmount?:{uiAmount?:number|null;uiAmountString?:string}}}}}};
type Pair={baseToken?:{address?:string;name?:string;symbol?:string};priceUsd?:string;marketCap?:number;fdv?:number;priceChange?:{h24?:number};liquidity?:{usd?:number};info?:{imageUrl?:string}};
type Holding={mint:string;balance:number;name:string;symbol:string;image:string;price:number;marketCap:number;change24h:number;value:number;supported:boolean};
const TOKEN_PROGRAM="TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",TOKEN_2022="TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",SOL_MINT="So11111111111111111111111111111111111111112";
const memory=new Map<string,{at:number;data:{holdings:Holding[];totalValue:number;updatedAt:string}}>();
const finite=(n:unknown)=>Number.isFinite(Number(n))?Number(n):0;
async function rpc(url:string,method:string,params:unknown[]){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:method+Math.random(),method,params}),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Solana RPC returned ${r.status}`);const j=await r.json() as {result?:unknown;error?:{message?:string}};if(j.error)throw new Error(j.error.message||"Solana RPC error");return j.result}
async function walletBalances(address:string){const configured=process.env.SOLANA_RPC_URL?.trim();const urls=[configured,"https://solana-rpc.publicnode.com","https://solana.drpc.org","https://api.mainnet-beta.solana.com"].filter((url,index,list):url is string=>Boolean(url)&&list.indexOf(url)===index);const config={encoding:"jsonParsed",commitment:"confirmed"};let lastError="Wallet balance service is temporarily unavailable";for(const url of urls){try{return await Promise.all([rpc(url,"getTokenAccountsByOwner",[address,{programId:TOKEN_PROGRAM},config]),rpc(url,"getTokenAccountsByOwner",[address,{programId:TOKEN_2022},config]),rpc(url,"getBalance",[address,{commitment:"confirmed"}])]) as [{value?:TokenAccount[]},{value?:TokenAccount[]},{value?:number}]}catch(error){lastError=error instanceof Error?error.message:lastError}}throw new Error(`${lastError}. Please try again shortly`)}
async function pairsFor(mints:string[]){const out:Pair[]=[];for(let i=0;i<mints.length;i+=30){const r=await fetch(`https://api.dexscreener.com/tokens/v1/solana/${mints.slice(i,i+30).join(",")}`,{headers:{Accept:"application/json","User-Agent":"MemeCoinPredictor/1.2"},signal:AbortSignal.timeout(10000)});if(r.ok)out.push(...await r.json() as Pair[])}return out}
export async function POST(request:Request){try{const body=await request.json() as {address?:string;balances?:{mint?:string;balance?:number}[]};const address=body.address?.trim()||"";if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address))return Response.json({error:"Invalid Solana wallet address"},{status:400});const supplied=Array.isArray(body.balances)?body.balances.slice(0,1000):null,cached=memory.get(address);if(!supplied&&cached&&Date.now()-cached.at<12000)return Response.json(cached.data,{headers:{"Cache-Control":"private, no-store"}});
 const balances=new Map<string,number>();if(supplied){for(const item of supplied){const mint=item.mint?.trim()||"",amount=finite(item.balance);if(/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(mint)&&amount>0)balances.set(mint,(balances.get(mint)||0)+amount)}}else{const[token1,token2,solResult]=await walletBalances(address);for(const item of[...(token1.value||[]),...(token2.value||[])]){const info=item.account?.data?.parsed?.info,mint=info?.mint,amount=finite(info?.tokenAmount?.uiAmount??info?.tokenAmount?.uiAmountString);if(mint&&amount>0)balances.set(mint,(balances.get(mint)||0)+amount)}const sol=finite(solResult.value)/1e9;if(sol>.000001)balances.set(SOL_MINT,sol)}
 const mints=[...balances.keys()],pairs=await pairsFor(mints),best=new Map<string,Pair>();for(const pair of pairs){const mint=pair.baseToken?.address;if(mint&&(!best.has(mint)||finite(pair.liquidity?.usd)>finite(best.get(mint)?.liquidity?.usd)))best.set(mint,pair)}
 const holdings=mints.map(mint=>{const pair=best.get(mint),balance=balances.get(mint)||0,price=finite(pair?.priceUsd);return{mint,balance,name:mint===SOL_MINT?"Solana":pair?.baseToken?.name||"Unknown token",symbol:mint===SOL_MINT?"SOL":pair?.baseToken?.symbol||`${mint.slice(0,4)}…`,image:pair?.info?.imageUrl||"",price,marketCap:finite(pair?.marketCap||pair?.fdv),change24h:finite(pair?.priceChange?.h24),value:balance*price,supported:Boolean(pair)}}).sort((a,b)=>b.value-a.value);const data={holdings,totalValue:holdings.reduce((s,h)=>s+h.value,0),updatedAt:new Date().toISOString()};memory.set(address,{at:Date.now(),data});return Response.json(data,{headers:{"Cache-Control":"private, no-store"}})
 }catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to load portfolio"},{status:503,headers:{"Cache-Control":"no-store"}})}}
